language: php

sudo: required

services:
    - docker

matrix:
  include:
    - php: 7.0
      env:
        - qaExtended=true
    - php: 7.1
    - php: 7.2
      env:
        - dropPlatform=false
    - php: 7.3
      env:
        - dropPlatform=false
    - php: nightly
      env:
        - dropPlatform=false
    - php: 7.0
      env:
        - dependencies=lowest
    - php: 7.1
      env:
        - dependencies=lowest
    - php: 7.2
      env:
        - dependencies=lowest
        - dropPlatform=false
    - php: 7.3
      env:
        - dependencies=lowest
        - dropPlatform=false
    - php: nightly
      env:
        - dependencies=lowest
        - dropPlatform=false
    - php: 7.0
      env:
        - dependencies=highest
    - php: 7.1
      env:
        - dependencies=highest
    - php: 7.2
      env:
        - dependencies=highest
        - dropPlatform=false
    - php: 7.3
      env:
        - dependencies=highest
        - dropPlatform=false
    - php: nightly
      env:
        - dependencies=highest
        - dropPlatform=false
  allow_failures:
    - php: nightly

before_install:
    - export PATH=$HOME/.local/bin:$PATH

before_script:
    - sh tests/Crossbar/travis_install
    - composer install

script:
    - php tests/TestServer.php 20 & vendor/bin/phpunit
    - sh tests/Crossbar/run_tests
